### ISSUE TITLE
Docker run not working

### ISSUE THREAD

**Issue by andradei** [tangramor/slidev_docker#5]
Following the documentation here: https://sli.dev/guide/install.html#install-on-docker

I ran the command below (added `--platform`)

```
docker run --name slidev --rm -it \
          --user node \
          --platform linux/amd64/v3 \
          -v (pwd):/slidev \
          -p 3030:3030 \
          tangramor/slidev:latest


Unable to find image 'tangramor/slidev:latest' locally
latest: Pulling from tangramor/slidev
c41833b44d91: Pull complete
762c2470eea4: Pull complete
fefc7d195eee: Pull complete
06fc22ed341f: Pull complete
768063141391: Pull complete
3837a9825463: Pull complete
78cf9c1f14c9: Pull complete
Digest: sha256:9cd1c610d197b0a343c0bea9a3049af709f779496e67242e5ec8e9eee51aac09
Status: Downloaded newer image for tangramor/slidev:latest


docker: image with reference tangramor/slidev was found but does not match the specified platform: wanted linux/amd64/v3, actual: linux/arm64/v8.
See 'docker run --help'.
```

**Comment by tangramor** [comment]
is there a reason for --platform option?
can the command work without it?

**Comment by St-ZFeng** [comment]
![image](https://github.com/tangramor/slidev_docker/assets/113660099/2e8e9e54-3f0f-4bb9-8cd5-6f51b6e16965)
The same. A bad thing.

**Comment by tangramor** [comment]
OK, I found the problem. The arm build image overwrote the default amd64 one...
I just pushed the amd64 build. Please try again. 

Sorry for the inconvenience.

**Comment by St-ZFeng** [comment]
![image](https://github.com/tangramor/slidev_docker/assets/113660099/21b1e2b2-a7c3-4bf1-8f1b-a297a5e5e6a7)
A new problem. Seems a permission issue.

**Comment by St-ZFeng** [comment]
I used `--user root`, and it worked. But it can't be accessed via the Internet.
![image](https://github.com/tangramor/slidev_docker/assets/113660099/3fcc4a16-19ff-4257-9f8c-9df43cabe87c)

**Comment by St-ZFeng** [comment]
#1 
An old problem. Thanks.

**Comment by tangramor** [comment]
> ![image](https://user-images.githubusercontent.com/113660099/241880290-21b1e2b2-a7c3-4bf1-8f1b-a297a5e5e6a7.png) A new problem. Seems a permission issue.

I am using WSL2 and the docker_run.sh works well for me. I am not sure what kind of docker env you are using...

**Comment by tangramor** [comment]
> #1 An old problem. Thanks.

This is really an annoying bug... I will find a way to fix it

**Comment by tangramor** [comment]
Fixed slides.md bug in the image script.
