### ISSUE TITLE
Add documentation for file watching

### ISSUE THREAD

**Issue by Ynn** [tangramor/slidev_docker#9]
It appears that file watching does not work as expected by default in Docker environments (tested on Windows 11).

To address this, it would be beneficial for the documentation to include a suggestion for enabling file watching in chokidar (used by slidev). Users can set the CHOKIDAR_USEPOLLING environment variable to true to activate polling, which can help in detecting file changes within Docker containers at the cost of CPU usage.

Here is an example Docker command that incorporates this workaround:

```shell
docker run --name slidev --rm -it -e CHOKIDAR_USEPOLLING=true --user node -v ${PWD}:/slidev -p 3030:3030 -e NPM_MIRROR="https://registry.npmmirror.com" tangramor/slidev:latest
```

**Comment by tangramor** [comment]
updated Dockerfile with "ENV CHOKIDAR_USEPOLLING=true"
